packages:
  - packages/core
  - packages/core-dev
  - packages/react
  - packages/react-dev
  - packages/jotai
  - packages/glossary
  - packages/glossary-query
  - packages/logger
  - example

overrides:
  esbuild@<=0.24.2: '>=0.25.0'
  # Prevent @types/react duplication by forcing single version
  "@types/react": "18.3.23"
