/**
 * Compatibility layer for Panda CSS recipes
 * This file re-exports recipes for backward compatibility
 */

export {
  containerRecipe as containerVariants,
  cardRecipe as cardVariants,
  buttonRecipe as buttonVariants,
  badgeRecipe as badgeVariants,
  inputRecipe as inputVariants,
  inputRecipe as textareaVariants,
  statusRecipe as statusVariants,
  gridRecipe as gridVariants,
  layoutRecipe as layoutVariants,
  sidebarRecipe as sidebarVariants,
  mainContentRecipe as mainContentVariants,
  navItemRecipe as navItemVariants,
  demoCardRecipe as demoCardVariants,
  codeExampleRecipe as codeExampleVariants,
  codeBlockRecipe as codeBlockVariants,
  toastRecipe as toastVariants,
  toastContainerRecipe as toastContainerVariants,
  toastStepBadgeRecipe as toastStepBadgeVariants,
  logMonitorRecipe as logMonitorVariants,
  logEntryRecipe as logEntryVariants,
  logLevelBadgeRecipe as logLevelBadgeVariants,
  type ContainerRecipeProps as ContainerVariants,
  type CardRecipeProps as CardVariants,
  type ButtonRecipeProps as ButtonVariants,
  type BadgeRecipeProps as BadgeVariants,
  type InputRecipeProps as InputVariants,
  type StatusRecipeProps as StatusVariants,
  type GridRecipeProps as GridVariants,
  type LayoutRecipeProps as LayoutVariants,
  type SidebarRecipeProps as SidebarVariants,
  type MainContentRecipeProps as MainContentVariants,
  type NavItemRecipeProps as NavItemVariants,
  type DemoCardRecipeProps as DemoCardVariants,
  type CodeExampleRecipeProps as CodeExampleVariants,
  type CodeBlockRecipeProps as CodeBlockVariants,
  type ToastRecipeProps as ToastVariants,
  type ToastContainerRecipeProps as ToastContainerVariants,
  type ToastStepBadgeRecipeProps as ToastStepBadgeVariants,
  type LogMonitorRecipeProps as LogMonitorVariants,
  type LogEntryRecipeProps as LogEntryVariants,
  type LogLevelBadgeRecipeProps as LogLevelBadgeVariants,
} from './recipes';
