/**
 * Help Display - Manages help text display
 */

export class HelpDisplay {
  show(): void {
    console.log('');
    console.log('🚀 LLMS Generator - Core Commands (Optimized)');
    console.log('');
    console.log('PROJECT INITIALIZATION:');
    console.log('  init [options]                   Initialize complete project (discovery → priority → templates)');
    console.log('                                   [--dry-run] [--overwrite] [--quiet]');
    console.log('                                   [--skip-discovery] [--skip-priority] [--skip-templates]');
    console.log('');
    console.log('WORKFLOW MANAGEMENT:');
    console.log('  work-next [options]              Find next document to work on');
    console.log('                                   [-l, --language <lang>] [--show-completed] [-v, --verbose]');
    console.log('');
    console.log('TEMPLATE MANAGEMENT (RECOMMENDED DEFAULT):');
    console.log('  generate-templates [options]     Generate template files for all documents (DEFAULT WORKFLOW)');
    console.log('                                   [-l, --language <lang>] [--category <cat>] [--character-limits <nums>]');
    console.log('                                   [--overwrite] [--dry-run] [-v, --verbose]');
    console.log('');
    console.log('  fill-templates [options]         Fill empty template files with content from source documents');
    console.log('                                   [-l, --language <lang>] [--category <cat>] [-c, --character-limit <num>]');
    console.log('                                   [--dry-run] [--overwrite] [-v, --verbose]');
    console.log('');
    console.log('LLMS GENERATION:');
    console.log('  clean-llms-generate [char-limit] [options]');
    console.log('                                   Generate clean LLMS files for LLM training (no metadata)');
    console.log('                                   [-l, --language <lang>] [-c, --category <cat>]');
    console.log('                                   [-p, --pattern clean|minimal|raw] [--dry-run] [-v, --verbose]');
    console.log('');
    console.log('  llms-generate [options]          Generate standard LLMS files with metadata');
    console.log('                                   [-c, --character-limit <num>] [--category <cat>]');
    console.log('                                   [-l, --language <lang>] [-p, --pattern standard|minimum|origin]');
    console.log('                                   [--dry-run] [-v, --verbose]');
    console.log('');
    console.log('EXAMPLES:');
    console.log('  # 🚀 RECOMMENDED WORKFLOW (Complete setup)');
    console.log('  npx @context-action/llms-generator init');
    console.log('  npx @context-action/llms-generator generate-templates  # Generate all template files');
    console.log('  npx @context-action/llms-generator llms-generate  # Generate final LLMS files');
    console.log('');
    console.log('  # Preview and control generation');
    console.log('  npx @context-action/llms-generator generate-templates --dry-run  # Preview what will be created');
    console.log('  npx @context-action/llms-generator generate-templates --overwrite  # Force overwrite existing files');
    console.log('');
    console.log('  # Find next document to work on');
    console.log('  npx @context-action/llms-generator work-next --language ko');
    console.log('');
    console.log('  # Generate template files (batch creation)');
    console.log('  npx @context-action/llms-generator generate-templates --language en');
    console.log('  npx @context-action/llms-generator generate-templates --category api --character-limits 100,300,500');
    console.log('  npx @context-action/llms-generator generate-templates --overwrite --dry-run');
    console.log('');
    console.log('  # Fill empty templates with content');
    console.log('  npx @context-action/llms-generator fill-templates --language en');
    console.log('  npx @context-action/llms-generator fill-templates --category api --character-limit 100 --dry-run');
    console.log('');
    console.log('  # Generate clean LLMS for LLM training (recommended)');
    console.log('  npx @context-action/llms-generator clean-llms-generate 300 --language ko --pattern clean');
    console.log('  npx @context-action/llms-generator clean-llms-generate --category guide --pattern minimal');
    console.log('  npx @context-action/llms-generator clean-llms-generate 100 --pattern raw --dry-run');
    console.log('');
    console.log('  # Generate standard LLMS with metadata');
    console.log('  npx @context-action/llms-generator llms-generate --character-limit 300 --language ko');
    console.log('  npx @context-action/llms-generator llms-generate --category guide --pattern minimum');
    console.log('');
    console.log('INIT COMMAND DETAILS:');
    console.log('  The init command performs three main steps:');
    console.log('  1. 📚 Document Discovery - Scans docs/ directory for all .md files');
    console.log('  2. 📊 Priority Generation - Creates priority.json files with metadata');
    console.log('  3. 📝 Template Creation - Generates template files for all character limits');
    console.log('');
    console.log('  Init options:');
    console.log('    --dry-run         Preview what will be created without making changes');
    console.log('    --overwrite       Overwrite existing priority.json files');
    console.log('    --quiet           Reduce output verbosity');
    console.log('    --skip-discovery  Skip document discovery step');
    console.log('    --skip-priority   Skip priority JSON generation step');
    console.log('    --skip-templates  Skip template generation step');
    console.log('');
    console.log('For more detailed options, use --help with specific commands:');
    console.log('  npx @context-action/llms-generator clean-llms-generate --help');
    console.log('');
    console.log('🎯 TYPICAL WORKFLOW:');
    console.log('  1. Run "init" to set up priority.json files for all documents');
    console.log('  2. Run "generate-templates" to create all template files (DEFAULT RECOMMENDED)');
    console.log('  3. Use "work-next" to find documents that need manual review');
    console.log('  4. Edit template files to add or refine content (optional)');
    console.log('  5. Generate LLMS files with "llms-generate" or "clean-llms-generate"');
    console.log('');
    console.log('💡 Note: This is the optimized CLI with only core, tested functionality');
    console.log('   Reduced from ~2000 lines to ~200 lines for better maintainability');
    console.log('');
  }
}