import assert from 'node:assert/strict';
import { mkdir, mkdtemp, readFile, realpath, rm, symlink, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import test from 'node:test';

import {
  analyzeHistoricalProjects,
  GitHistoryReader,
  GitWorktreeManager,
  RepositoryRevisionReader,
  sameRepositoryRevision,
} from '../dist/index.js';

function git(cwd, args) {
  const result = spawnSync('git', args, { cwd, encoding: 'utf8' });
  assert.equal(result.status, 0, result.stderr);
  return result.stdout.trim();
}

async function fixtureRepository() {
  const root = await mkdtemp(path.join(os.tmpdir(), 'sem-foundation-repository-test-'));
  git(root, ['init', '--quiet']);
  git(root, ['config', 'user.email', 'test@example.com']);
  git(root, ['config', 'user.name', 'Repository Test']);
  await mkdir(path.join(root, 'packages', 'core'), { recursive: true });
  await writeFile(path.join(root, 'packages', 'core', 'index.ts'), 'export const version = 1;\n');
  git(root, ['add', '.']);
  git(root, ['commit', '--quiet', '-m', 'initial']);
  const first = git(root, ['rev-parse', 'HEAD']);
  await writeFile(path.join(root, 'packages', 'core', 'index.ts'), 'export const version = 2;\n');
  git(root, ['add', '.']);
  git(root, ['commit', '--quiet', '-m', 'update']);
  const second = git(root, ['rev-parse', 'HEAD']);
  return { root, first, second };
}

test('reads bounded first-parent history and materializes project snapshots', async (t) => {
  const fixture = await fixtureRepository();
  t.after(() => rm(fixture.root, { recursive: true, force: true }));

  const commits = new GitHistoryReader().listRange({
    repositoryRoot: fixture.root,
    from: fixture.first,
    to: fixture.second,
  });
  assert.equal(commits.length, 1);
  assert.equal(commits[0].subject, 'update');

  const snapshots = await new GitWorktreeManager(fixture.root).withCommitRange(
    commits,
    (commit, worktreeRoot) => analyzeHistoricalProjects({
      commit: commit.commit,
      worktreeRoot,
      projects: [{ id: 'core', root: 'packages/core' }],
      analyze: async ({ projectRoot }) => readFile(path.join(projectRoot, 'index.ts'), 'utf8'),
    }),
  );
  assert.equal(snapshots.length, 1);
  assert.equal(snapshots[0][0].value, 'export const version = 2;\n');
});

test('resolves symbolic Git refs before materializing a commit worktree', async (t) => {
  const fixture = await fixtureRepository();
  t.after(() => rm(fixture.root, { recursive: true, force: true }));

  const manager = new GitWorktreeManager(fixture.root);
  assert.equal(manager.resolveCommit('HEAD~1'), fixture.first);
  const content = await manager.withCommit('HEAD~1', (worktreeRoot) =>
    readFile(path.join(worktreeRoot, 'packages/core/index.ts'), 'utf8'));
  assert.equal(content, 'export const version = 1;\n');
});

test('isolates untracked analysis artifacts between historical commits', async (t) => {
  const fixture = await fixtureRepository();
  t.after(() => rm(fixture.root, { recursive: true, force: true }));

  const commits = [
    { commit: fixture.first, parent: fixture.first, subject: 'first' },
    { commit: fixture.second, parent: fixture.first, subject: 'second' },
  ];
  const seenArtifacts = await new GitWorktreeManager(fixture.root).withCommitRange(
    commits,
    async (_commit, worktreeRoot) => {
      const marker = path.join(worktreeRoot, 'analysis-artifact.tmp');
      const existedBefore = await readFile(marker, 'utf8').then(() => true, () => false);
      await writeFile(marker, 'generated by analysis');
      return existedBefore;
    },
  );
  assert.deepEqual(seenArtifacts, [false, false]);
});

test('captures a stable repository revision and rejects project symlink escapes', async (t) => {
  const fixture = await fixtureRepository();
  t.after(() => rm(fixture.root, { recursive: true, force: true }));

  const reader = new RepositoryRevisionReader();
  assert.equal(
    reader.resolveRepositoryRoot(path.join(fixture.root, 'packages/core')),
    await realpath(fixture.root),
  );
  const before = reader.read(fixture.root);
  const after = reader.read(fixture.root);
  assert.equal(sameRepositoryRevision(before, after), true);

  await assert.rejects(
    () => analyzeHistoricalProjects({
      commit: fixture.second,
      worktreeRoot: fixture.root,
      projects: [{ id: 'escape', root: '../outside' }],
      analyze: () => 'unreachable',
    }),
    /escapes its root/,
  );
});

test('revision digest rejects untracked symlinks that escape the repository', async (t) => {
  if (process.platform === 'win32') {
    t.skip('Windows symlink creation requires elevated privileges');
    return;
  }
  const fixture = await fixtureRepository();
  t.after(() => rm(fixture.root, { recursive: true, force: true }));
  const outside = await mkdtemp(path.join(os.tmpdir(), 'sem-foundation-repository-outside-'));
  t.after(() => rm(outside, { recursive: true, force: true }));
  await writeFile(path.join(outside, 'secret.ts'), 'export const secret = true;\n');
  await symlink(path.join(outside, 'secret.ts'), path.join(fixture.root, 'linked.ts'));
  assert.throws(() => new RepositoryRevisionReader().read(fixture.root), /through a symlink/);
});

test('reads an unborn repository without treating the missing HEAD as a Git failure', async (t) => {
  const root = await mkdtemp(path.join(os.tmpdir(), 'sem-foundation-unborn-'));
  t.after(() => rm(root, { recursive: true, force: true }));
  git(root, ['init', '--quiet']);
  await writeFile(path.join(root, 'README.md'), '# Unborn\n');
  const revision = new RepositoryRevisionReader().read(root);
  assert.equal(revision.gitHead, 'UNBORN');
  assert.equal(typeof revision.workingTreeDigest, 'string');
  git(root, ['add', 'README.md']);
  const stagedRevision = new RepositoryRevisionReader().read(root);
  assert.notEqual(stagedRevision.workingTreeDigest, revision.workingTreeDigest);
});
