name: Update LLMs Documentation Status

on:
  # Temporarily disabled - enable manually when needed
  workflow_dispatch:
  # push:
  #   paths:
  #     - 'docs/**/*.md'
  #     - '!docs/**/llms/**'
  #   branches:
  #     - main
  #     - develop

jobs:
  update-llms-status:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    
    - uses: pnpm/action-setup@v2
      with:
        version: 9
    
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'
    
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    
    - name: Build llms-generator
      run: pnpm build:llms-generator
    
    - name: Get changed files
      id: changed-files
      run: |
        echo "files=$(git diff --name-only HEAD^ HEAD | grep -E '^docs/.*\.md$' | grep -v llms/ | tr '\n' ' ')" >> $GITHUB_OUTPUT
    
    - name: Update work status for changed files
      run: |
        for file in ${{ steps.changed-files.outputs.files }}; do
          echo "Processing: $file"
          # Extract language and document ID from path
          if [[ $file =~ docs/(en|ko)/(.+)\.md$ ]]; then
            lang="${BASH_REMATCH[1]}"
            doc_path="${BASH_REMATCH[2]}"
            doc_id=$(echo "$doc_path" | sed 's/\//-/g')
            
            echo "Updating status for $lang/$doc_id"
            node packages/llms-generator/dist/cli/index.js work-update $lang $doc_id --source-modified
          fi
        done
    
    - name: Commit status updates
      run: |
        git config --local user.email "mineclover@naver.com"
        git config --local user.name "GitHub Action"
        # Check if priority.json files exist before trying to add them
        if ls packages/llms-generator/data/*/priority.json 1> /dev/null 2>&1; then
          git add packages/llms-generator/data/*/priority.json
        fi
        # Also check for any other generated files
        git add packages/llms-generator/data/ || true
        if ! git diff --staged --quiet; then
          git commit -m "chore: update LLMs work status for modified documents"
          git push
        else
          echo "No changes to commit"
        fi